### ISSUE TITLE
C function system() and Ubuntu 16.04

### ISSUE THREAD

**Issue by tsnouidui** [lbl-srg/EnergyPlusToFMU#12]
EnergyPlusToFMU leverages the C-function` system()` to run EnergyPlus as an FMU. This function doesn't seem to work on Ubuntu 16.04. Consequently, EnergyplusToFMU fails to run on this OS. The behavior can't be reproduced on Ubuntu 14.04.

**Comment by krzysztofarendt** [comment]
Just a comment: I run EnergyPlusToFMU v.2.0.2 on Ubuntu 16.04 64bit without any issues. It works right out of the box.

**Comment by tsnouidui** [comment]
Interesting. On my computer I had issues running it. Maybe it is my system which is broken. I will test it on a different machine which has Ubuntu 16.04 to see if I can reproduce the issue.
Thanks
