### ISSUE TITLE
Exporting an EnergyPlus 9.0.1 model is not supported

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/EnergyPlusToFMU#24]
EnergyPlus 9.0 changed the idd entry for the RunPeriod, EnergyPlusToFMU which has been tested with EnergyPlus 8.0 expects a different entry and then stops with the error
```
$ /opt/EnergyPlusToFMU-v2.0.3/Scripts/EnergyPlusToFMU.py -i Energy+.idd -w in.epw in.idf 
Reading input and weather file for EnergyPlusToFMU program.
Incompatible IDD file /home/mwetter/Downloads/fmu_exp_ep901/Energy+.idd
For key 'RUNPERIOD', input data dictionary has descriptor 'ANNNNNNAAAAAAA', but expecting 'ANNNNAAAAAANAN'
ERROR from script file {EnergyPlusToFMU.py}
Failed to extract FMU information from IDF file {/home/mwetter/Downloads/fmu_exp_ep901/in.idf}
```

**Comment by tsnouidui** [comment]
@mwetter Could you please checkout branch https://github.com/lbl-srg/EnergyPlusToFMU/tree/issue4_idd to see if you are still observing the same problem? This fix should work for past and current versions of E+.
