### ISSUE TITLE
How to use gcc(instead of VS2010) in windows to creat an FMU

### ISSUE THREAD

**Issue by jywang2016** [lbl-srg/EnergyPlusToFMU#25]
Hi

Thanks for your great work! I am a windows10 user and the `EnergyPlusToFMU` works well with Microsoft Visual Studio 2010. However, I wonder is there a way to create an FMU with gcc compiler for windows users ?

I have no idea about how to modify the `batch files` and I cannot find any info in the `userGuide` of `EnergyPlusToFMU`.

Regrads,
JY

**Comment by tsnouidui** [comment]
Out of curiosity why aren't you using Visual Studio 2015 Express which is free if you need a free solution?Do you need gcc in the loop absolutely?
Thanks!
Thierry

    Am Donnerstag, 13. Dezember 2018, 14:58:07 GMT+3 hat Jiangyu Wang <notifications@github.com> Folgendes geschrieben:  
 
 
Hi

Thanks for your great work! I am a windows10 user and the EnergyPlusToFMU works well with Microsoft Visual Studio 2010. However, I wonder is that a way to create an FMU with gcc compiler for windows.

I have no idea about how to modify the batch files and I cannot find any info in the userGuide of EnergyPlusToFMU.

Regrads,
JY

**Comment by jywang2016** [comment]
Thanks for your reply. 

In fact, the [Rtools](https://cran.r-project.org/bin/windows/Rtools/) provides gcc compiler for `R` user. If gcc can work well with EnergyPlusToFMU on windows, all R-users can export FMU without additive installation of VS 10 or VS 15 Express in windows. 

In other word, I want find a minimum way to do the co-simulation in `R` environment. With VS 10 and [reticulate](https://rstudio.github.io/reticulate/) package(enable R use pyFMI package), I already conduct the co-simulation in R successfully. Now, I want replace the "redundant one" ,namely VS,  with gcc to minimize the whole toolchain.

Regrads,
JY

**Comment by tsnouidui** [comment]
If you haven't found a solution yet, I suggest to look at the Linux Scripts (https://github.com/lbl-srg/EnergyPlusToFMU/tree/master/Scripts/linux) which are set-up to use gcc.

**Comment by jywang2016** [comment]
Thanks for your reply.  I will have a try.
