### ISSUE TITLE
Problems running FMU exported using EnergyPlus 9.0.1

### ISSUE THREAD

**Issue by anoushp** [lbl-srg/EnergyPlusToFMU#31]
Hello,

I compiled FMU using EnergyPlusToFMU-v2.1.0 and having EnergyPlus 9.0.1 installed on my computer. The compilation was successful. Now I am attempting running FMU/cosimulation and I am getting the following error "energyplus -w runweafile.epw -p testoffice2 -s C -x -m -r testoffice2.idf 'energyplus' is not recognized as an internal or external command"
Or if I try running co simulation using FMpy package I get 'This version uses the **energyplus** command line interface to  call the EnergyPlus executable. **RunEPlus.bat** and **runenergyplus** , which were used in earlier versions, were deprecated as of August 2015.'

I understand that the problem is in EP.bat file that call energyplus command. I am not sure if there is a workaround to this?

Thanks,

**Comment by tsnouidui** [comment]
Please add EnergyPlus to your system path so it can be invoked by the FMU.
See No.1 of the userguide http://simulationresearch.lbl.gov/fmu/EnergyPlus/export/userGuide/usage.html

**Comment by anoushp** [comment]
Thanks! It solved the problem.
