### ISSUE TITLE
Communicationstepsize: %f is different from time step: %d in input file

### ISSUE THREAD

**Issue by quyenanh98** [lbl-srg/EnergyPlusToFMU#33]

**Comment by quyenanh98** [comment]
Hello,
I tried to simulate my fmu file using this command : res = model.simulate(final_time=86400) in python (pyFMI). 
I dont understand why this error appears

[ERROR][Slave] [error][FMU status:Error] fmiDoStep: An error occured in a previous call. CommunicationStepSize: 172.800000 is different from time step: 6 in input file.

Here is the idf file that I used (I changed the extention to txt to upload it here).

Can anyone please advice if I have done anything wrong, whty fmiDoStep happens in my case, and how I can fix it.

[greenerallparametersfrequencyresponsedetailed.txt](https://github.com/lbl-srg/EnergyPlusToFMU/files/3262071/greenerallparametersfrequencyresponsedetailed.txt)

![image](https://user-images.githubusercontent.com/23640412/59040807-bde68e00-8877-11e9-9c92-6c67296f6ef5.png)

**Comment by tsnouidui** [comment]
Your number of communication points is probably not matching the time step. What you need to do is 

1. _Get the model options object_
`opts = model.simulate_options()`

1. _Compute the number of communication points_ 
`ncp = final_time/idf_steps_per_seconds` (e.g. for 15 minutes time step, idf_steps_per_seconds would be 15*60 = 900s)

1. _Store the communication points_ 
`opts['ncp'] = ncp`

1. _run simulation where you will pass the number of communication points to the model_
`res = model.simulate(final_time=final_time, options=opts)`

This thread may be useful as well

https://groups.google.com/forum/#!topic/energyplus-fmu/fSNam7XHvgg

**Comment by quyenanh98** [comment]
the time step defined in my idf is 6, so I changed the ncp to 600. However the error remains pretty similar but the communicationstepsize is different now.

[ERROR][Slave] [error][FMU status:Error] fmiDoStep: An error occured in a previous call. CommunicationStepSize: 144.000000 is different from time step: 6 in input file.

![image](https://user-images.githubusercontent.com/23640412/59059901-2ea1a080-88a0-11e9-9531-e0692aacae13.png)

**Comment by quyenanh98** [comment]
Thank you so much, it works

**Comment by tsnouidui** [comment]
@quyenanh98 Should the issue be closed?
