### ISSUE TITLE
Add support for FMI 2.0

### ISSUE THREAD

**Issue by tsnouidui** [lbl-srg/EnergyPlusToFMU#35]
This issue is to add support for FMI 2.0 for Co-Simulation.

**Comment by brianlball** [comment]
Is this being developed at all?

**Comment by mwetter** [comment]
We like to develop it this FY if resources allow.

**Comment by brianlball** [comment]
Have seen some activity in this branch https://github.com/lbl-srg/EnergyPlusToFMU/tree/issue35  :)  
@tsnouidui do you have an idea on when this would be ready for general release?  Also, thanks for your efforts on this!

**Comment by tsnouidui** [comment]
@brianlball. Thanks for the note. 
Yes I am currently working on the FMI 2.0 for Co-simulation extension for E+ToFMU. 
A general release may be around March/April next year (potentially earlier)... 
What is your intended application, just out of curiosity?

**Comment by brianlball** [comment]
good to know.  We are working on getting FMU co-sim to work in OpenStudio Server.
Going to have to use FMPy until we can get an E+ FMU 2.0 CS, since pyFMI only does coupled co-sim with 2.0

**Comment by tsnouidui** [comment]
Sounds good. Will keep you posted in case of an early release.

**Comment by fabianoP** [comment]
Hi any news on this release? Thanks for the effort. Fabiano

**Comment by tsnouidui** [comment]
We are doing some final testing on Mac OS X and will release it soon.

**Comment by fabianoP** [comment]
Thanks
