### ISSUE TITLE
Issues running  FMUs(from EnergyPlusToFMU2.1.0) on Pyfmi 

### ISSUE THREAD

**Issue by tongue01** [lbl-srg/EnergyPlusToFMU#40]
I used the latest version of E+ and EnergyPlusToFMU2.1.0 , and tried to co-simulation with the pyfmi2.4 and the fmus than i created. but there was an error on the load_fmu():UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 27: invalid start byte.
![image](https://user-images.githubusercontent.com/47770934/75556987-33cffc80-5a7a-11ea-93cf-0aff5854b8f3.png)
i m sure that the pyfmi is correctly installed, so do you know why?

**Comment by tsnouidui** [comment]
I have never seen such an error. Which version of Python are you using? Could you share the master algorithm code you are using to drive the FMU?
