### ISSUE TITLE
Create FMU with external schedule file

### ISSUE THREAD

**Issue by kuzha** [lbl-srg/EnergyPlusToFMU#42]
EnergyPlus Schedules has an object Schedule:File, which allows to simulate schedules from external data source, such as stochastic schedule.

Is it possible to create an FMU using this object Schedule:File with an external csv file? I did not find any command to allow adding external data file except weather and idd file.

**Comment by mwetter** [comment]
I don't think external files will be copied into the FMU, but you could try to create the fmu, unzip it, add the file and zip it again.

**Comment by tsnouidui** [comment]
@mwetter is correct. External file won't be copied to the FMU. Another alternative could be to define an absolute path in the IDF file which will point to the csv file. This will make the FMU not portable though.
