### ISSUE TITLE
FMU1.0 and 2.0 - warning messages

### ISSUE THREAD

**Issue by xavfa** [lbl-srg/EnergyPlusToFMU#59]
Hi to all,
I was used to make FMU1.0 and running them under FMI++. Worked fine, no warning messages during either the FMU building process or the simulation process afterward. In order to make my work compatible on Linux I had to change my FMU's playground to FMPy. FMU version 1.0 and 2.0 are working well. FMPy works great on both Linux and Windows with a quite ease installation process (pip install !).
But I am facing small things on which I have doubts on the importance's:
1 - During the FMU building process, only for FMU2.0 : 
on windows I get the following messages 
`
! makeFMULib.py -- Link with the libxml2.lib located in {c:\users\xav77\documents\faure\prgm_python\urbant\eplus4mubes\fmuskit\energyplustofmu-v3.1.0\Scripts\..\SourceCode\v20\fmusdk-shared\parser\win64\libxml2.lib}
   Creating library Building_28v0.lib and object Building_28v0.exp
LINK : warning LNK4217: symbol 'xmlFree' defined in 'libxml2.lib(globals.obj)' is imported by 'xmlVersionParser.obj' in function '"char * __cdecl extractFmiVersionAttribute(struct _xmlTextReader *)" (?extractFmiVersionAttribute@@YAPEADPEAU_xmlTextReader@@@Z)'
LINK : warning LNK4286: symbol 'xmlFree' defined in 'libxml2.lib(globals.obj)' is imported by 'XmlParser.obj'
`
while on linux I get several warning messages from strncpy() C function that is called in findNameFile() and getResourceLocation() (I don't copy/paste them as there are quite some lines)

2- During the simulation, for both version 1.0 and 2.0, I get for each FMUs initialization stage, this message, coming from FMPy but prewritten in the main.c in EPlusFMUToolKit SourceCode :
` This version uses the **energyplus** command line interface to  call the EnergyPlus executable. **RunEPlus.bat** and **runenergyplus** , which were used in earlier versions, were deprecated as of August 2015.`

But for all cases, I can run the simulation to its end and results are identical.

Please, what is the importance of these messages on both the FMU building process and during the initialization, and is it worth using version 2.0 (as from https://www.modelon.com/functional-mock-up-interface-fmi/, we could thought that using 2.0 is recommended)  ?
Thanks in advance
Xavier

**Comment by tsnouidui** [comment]
The warnings can be safely ignored and some will be removed in future releases. 

Whether you should use FMI 1.0 or 2.0 depends also on the master and the simulation scenario you want to run. For instance if you want to couple two FMUs using PyFMI and its `Master` object for co-simulation, you will have to have all your FMUs exported as FMUs 2.0 for co-simulation.

By the way, could you let me know the version of FMPy you are using to run your FMUs?
I am also interested in the version of Python you used to install that specific version of FMPy.
Lastly, please share the master algorithm code you have used to drive the EnergyPlusFMU using FMPy.
I would like to see the FMPy functions you have called as I was having some issues running some EnergyPlusFMUs with it.

**Comment by xavfa** [comment]
Hi,
thanks for the answer and to know that the warnings can be ignored (in Linux it is still scary as a bunch of red line are popped out...).
For Linux I have tested it on ORACLE VM, Ubuntu (hosted by Windows10). with python 3.8.10 and FMPy 0.3.1
For Windows 10, it works with python 3.7.1 and FMPy 0.3.1
the two python versions simply come from the available versions when needed on the computers, I didn't search for specific version while installing it.
Please find below the master code I tried from now. It is built as a simple example to check the good behavior, I haven't made any deep study with it yet, but I wanted to offer the possibility to my colleagues and students to make co-simulation and test EMS at the district level. This example deals only with Temperature set points of buildings. I have another one with 2 inputs to each FMUs (but the FMPy functions remain the sames).
I'm not sure to understand (could you orient me towards literature that could give me examples?) 

> Whether you should use FMI 1.0 or 2.0 depends also on the master and the simulation scenario you want to run. For instance if you want to couple two FMUs using PyFMI and its Master object for co-simulation, you will have to have all your FMUs exported as FMUs 2.0 for co-simulation.

```
`""" This example uses FMpy as a environment to make FMU simulation. It deals only with
 changing the set point for 2 hours for each building one after the other. Thus setPoint changes' frequency depends
 on the number of FMU considered in total."""


import os,sys
from fmpy import read_model_description, extract
from fmpy.fmi1 import FMU1Slave
from fmpy.fmi2 import FMU2Slave
path2addgeom = os.path.join(os.path.dirname(os.path.dirname(os.getcwd())),'geomeppy')
sys.path.append(path2addgeom)
sys.path.append('..')
import shutil
import pickle
import time as timedelay
from CoreFiles import LaunchSim as LaunchSim

def InstAndInitiV1(filelist,VarNames,start_time,stop_time) :
    idx1 = ['_', 'v']
    fmunNb = 0
    FMUElement = {}
    for file in filelist:
        if file[-4:] == '.fmu':
            fmunNb += 1
            model_name = file[:-4]
            FMUKeyName = int(model_name[model_name.index(idx1[0]) + 1:model_name.index(idx1[1])])
            FMUElement[FMUKeyName] = {}
            model_description = read_model_description(file)
            FMUElement[FMUKeyName]['unzipdir'] = extract(file)
            vrs = {}
            for variable in model_description.modelVariables:
                vrs[variable.name] = variable.valueReference
            FMUElement[FMUKeyName]['Exch_Var'] = vrs
            FMUElement[FMUKeyName]['fmu'] = FMU1Slave(guid=model_description.guid,
                            unzipDirectory=FMUElement[FMUKeyName]['unzipdir'],
                            modelIdentifier=model_description.coSimulation.modelIdentifier,
                            instanceName=model_name)
            FMUElement[FMUKeyName]['fmu'].instantiate()
            FMUElement[FMUKeyName]['fmu'].setReal([vrs[VarNames['Inputs'][0]]],[21])
            FMUElement[FMUKeyName]['fmu'].initialize(tStart=start_time, stopTime=stop_time)
    return  FMUElement

def InstAndInitiV2(filelist,VarNames,start_time,stop_time) :
    idx1 = ['_', 'v']
    fmunNb = 0
    FMUElement = {}
    for file in filelist:
        if file[-4:] == '.fmu':
            fmunNb += 1
            model_name = file[:-4]
            FMUKeyName = int(model_name[model_name.index(idx1[0]) + 1:model_name.index(idx1[1])])
            FMUElement[FMUKeyName] = {}
            model_description = read_model_description(file)
            FMUElement[FMUKeyName]['unzipdir'] = extract(file)
            vrs = {}
            for variable in model_description.modelVariables:
                vrs[variable.name] = variable.valueReference
            FMUElement[FMUKeyName]['Exch_Var'] = vrs
            FMUElement[FMUKeyName]['fmu'] = FMU2Slave(guid=model_description.guid,
                            unzipDirectory=FMUElement[FMUKeyName]['unzipdir'],
                            modelIdentifier=model_description.coSimulation.modelIdentifier,
                            instanceName=model_name)
            FMUElement[FMUKeyName]['fmu'].instantiate()
            FMUElement[FMUKeyName]['fmu'].setupExperiment(startTime=start_time, stopTime=stop_time)
            FMUElement[FMUKeyName]['fmu'].setReal([vrs[VarNames['Inputs'][0]]],[21])
            FMUElement[FMUKeyName]['fmu'].enterInitializationMode()
            FMUElement[FMUKeyName]['fmu'].exitInitializationMode()
    return  FMUElement

def LaunchFMU_Sim(FMUElement,VarNames, start_time,stop_time,step_size):
    time = start_time
    day = 0
    SetPoints = {}
    MeanTemp = {}
    HeatPow = {}
    bld = 0
    for key in FMUElement.keys():
        HeatPow[key] = [0]
        MeanTemp[key] = [0]
        SetPoints[key] = [21]
    # simulation loop
    while time < stop_time:
        if (time % (240 * 3600)) == 0:
            day += 10
            print(str(day) + ' simulation days done')
        if time % (2 * 3600) == 0:
            bld += 1
            bld = bld % len(FMUElement.keys())
        for i, key in enumerate(FMUElement.keys()):
            SetPoints[key].append(21)
            if i == bld:
                SetPoints[key].append(18)
            FMUElement[key]['fmu'].setReal([FMUElement[key]['Exch_Var']['TempSetPoint']], [SetPoints[key][-1]])
            FMUElement[key]['fmu'].doStep(currentCommunicationPoint=time, communicationStepSize=step_size)
            #lets catch the outputs (even if not used in this example, it could be used to control the next inputs)
            MeanTemp[key].append(FMUElement[key]['fmu'].getReal([FMUElement[key]['Exch_Var'][VarNames['Outputs'][0]]]))
            HeatPow[key].append(FMUElement[key]['fmu'].getReal([FMUElement[key]['Exch_Var'][VarNames['Outputs'][1]]]))
        time += step_size
    for i, key in enumerate(FMUElement.keys()):
        FMUElement[key]['fmu'].terminate()
        FMUElement[key]['fmu'].freeInstance()
        shutil.rmtree(FMUElement[key]['unzipdir'] , ignore_errors=True)
    return time

def CleanUpSimRes(work_dir,keepLogFolder = False):
  #now lets clean up all the folders and files
  print('################################################')
  print('Starting the cleanup process')
  timedelay.sleep(5)
  ResSimpath = os.path.join(work_dir,'Sim_Results')
  if not os.path.exists(ResSimpath):
    os.mkdir(ResSimpath)
  liste = os.listdir()
  for file in liste:
    if 'Output_EPExport_' in file:
      buildName = file[len('Output_EPExport_'):]
      buildNameidf = buildName+'.idf'
      with open(os.path.join(work_dir,buildName+'.pickle'), 'rb') as handle:
           loadB = pickle.load(handle)
      building = loadB['BuildData']
      building.SaveLogFiles = keepLogFolder
      LaunchSim.savecase(buildName,os.path.join(work_dir,file),building,ResSimpath,buildNameidf,work_dir,withFMU = True)
      #unable to erase the fmu extracted folder as the dll is still open at this stage of the code....why ? still weird to me
      #shutil.rmtree(buildName)

if __name__ == '__main__':
    MainPath = os.getcwd()
    SavedFolder = 'MUBES_SimResults/ForTest'
    work_dir = os.path.normcase(
        os.path.join(os.path.dirname(os.path.dirname(MainPath)), SavedFolder))
    os.chdir(work_dir)
    filelist = os.listdir(work_dir)
    start_time = 0*24*3600
    stop_time =  100*24*3600
    step_size = 900
    VarNames = {'Inputs': ['TempSetPoint'], 'Outputs' : ['MeanBldTemp', 'HeatingPower']}
    #to make it work if being either version1.0 or 2.0 or FMU Standards
    try:
        FMUElement = InstAndInitiV1(filelist,VarNames,start_time,stop_time)
    except:
        FMUElement = InstAndInitiV2(filelist,VarNames, start_time, stop_time)
    LaunchFMU_Sim(FMUElement,VarNames, start_time, stop_time, step_size)
    CleanUpSimRes(work_dir, keepLogFolder=True)
```
`

**Comment by xavfa** [comment]
I guess we can close this issue now.

**Comment by tsnouidui** [comment]
Thanks for the code. I see that you have used the low level functions of FMPy to drive the FMU. That is helpful.

As far as the note below is concerned. I was simply trying to say that the version of the FMI you use depends also on the master that you will use to drive the FMU. For instance, some master algorithms only support FMI 1.0, some support co-simulation but only if the FMU is a 2.0 FMU. 
I have made referenced to PyFMI for simulation of coupled FMU because they have developed a nice API which allows to conveniently simulated multiple FMUs. The requirement is that all those FMUs need to be exported as FMUs that implement the FMI 2.0 for Co-simulation.
Check out this thread which shows how you could use PyFMI to run such case https://www.modelon.com/co-simulation-using-the-open-source-python-package-pyfmi/


> I'm not sure to understand (could you orient me towards literature that could give me examples?)
> 
> Whether you should use FMI 1.0 or 2.0 depends also on the master and the simulation scenario you want to run. For instance if you want to couple two FMUs using PyFMI and its Master object for co-simulation, you will have to have all your FMUs exported as FMUs 2.0 for co-simulation.
