### ISSUE TITLE
Error while creating FMU from Energyplus: Error from script file {makeFMULib.pyc}

### ISSUE THREAD

**Issue by AfshinGharib** [lbl-srg/EnergyPlusToFMU#60]
Hello guys,
I am trying to create a FMU from my Energy plus model (and weather file), I have done all the steps according to the file and at the last step when I enter the code in command window to creat FMU I receive an error that says "ERROR from script file {makeFMULib.pyc}, Failed to run utility application {c:\cosimulation\until-get-address-size.exe}: reason unknown"
Is it possible that you help me with this error.
![Capture](https://user-images.githubusercontent.com/90244595/132307926-4673045d-2432-448e-adba-8afef9351b48.JPG)

**Comment by AfshinGharib** [comment]
I have found the answer myself, i was using python 3.8 and i uninstalled it and installed python 2.7 and the problem got fixed

**Comment by tsnouidui** [comment]
The latest version of EnergyPlusToFMU works with both Python 2.7 and Python 3.x. I hence don't know why you had that problem in the first place. Glad that it is resolved but I suggest getting the latest version and trying with Python 3.x again.
