### ISSUE TITLE
Outputs do not change with inputs

### ISSUE THREAD

**Issue by yyuanjoy** [lbl-srg/EnergyPlusToFMU#7]
Hi Thierry

I use the "schedule" example to generated a FMU file, and then import this file into dymola.
Firstly, I found I have to change the .idf of the schedule example, because it is the v8-5-0, while I'm using v8-6-0. The input format for "other equipment" is different in these two version. If I kept the example unchanged, I can still generate the FMU, but dymola will stay as "initializing" and cannot get the results. 

Then, I used a real expression in dymola as the FMU input, but unfortunately, no matter how I change the input, the output, which is the Troom, never changes. 

[Test.zip](https://github.com/lbl-srg/EnergyPlusToFMU/files/878363/Test.zip)

I've attached the files I used in this test. Would you please kindly guide me what's wrong in my model? Thank you a lot!!

Best,
Yuan

**Comment by tsnouidui** [comment]
@yyuanjoy 
I looked at your `.mo` file and saw few issues:

The simulation stop time was set in the `.mo` file to be 86400s.
You set the` fmi_NumberOfSteps` to be 144 which implies a time step of 600s. 
However your IDF file had a time step of 15 minutes. 
So you need to change  `fmi_NumberOfSteps `to be 96.

I am not sure whether you set the simulation  `Stop time` in Dymola to also be 86400. 
This needs to be done too since Dymola does not propagate simulation settings to the FMU.
To change that, go to the Simulation Setup tab of Dymola, and set the simulation `Stop time` to match the time set in your FMU.

You will also need to set the output `Interval length` of Dymola to be 900. 
This will make sure that Dymola does not call the FMU at times different from the time step.

These changes should lead to following simulation command:

`simulateModel("fmutest", stopTime=86400, numberOfIntervals=0, outputInterval=900, method="dassl", resultFile="fmutest");`

I ran the example you sent without any issues.

**Comment by yyuanjoy** [comment]
@tsnouidui 

I've synchronized the time steps as you suggested. However, I still cannot impact the output by changing the input real expression. For example, the attached picture is the outputs of two simulation senario, where I set inputs as 1 and 2000, respectively. You can see that the output lines are exactly the same. If there any other possible error I could have made? Thank you!!

Best,
Yuan
![simulation_results](https://cloud.githubusercontent.com/assets/26762647/24844770/a9fbcdb0-1ddf-11e7-8f83-f8a7c92465a6.jpg)

**Comment by tsnouidui** [comment]
@yyuanjoy 

I looked at your IDf and saw following:

```
! ===============================================================
! Other Equipment to link FMU air system to this room model
! -- Sensible heat transfer
OtherEquipment,
    OthEquSen_ZoneOne,       !- Name
    None,                    !- Fuel Type
    ZONE ONE,                !- Zone or ZoneList Name
    Sch 1,                   !- Schedule Name
    EquipmentLevel,          !- Design Level Calculation Method
    1,                       !- Design Level {W}
    ,                        !- Power per Zone Floor Area {W/m2}
    0,                       !- Power per Person {W/Person}
    0,                       !- Fraction Latent
    0,                       !- Fraction Radiant
    ;                        !- Fraction Lost

ExternalInterface:FunctionalMockupUnitExport:To:Schedule,
    FMU_OthEqu_ZoneOne,      !- Schedule Name
    Fraction,                !- Schedule Type Limits Names
    Q,                       !- FMU Variable Name
    0;                       !- Initial Value
```

The `OtherEquipment `doesn't seem to be using the right schedule. It is set to use the `Schedule` with the name `Sch 1` whereas the `ExternalInterface`  Schedule's name is `FMU_OthEqu_ZoneOne`.

This might explain why you do not see any changes when changing inputs.

**Comment by yyuanjoy** [comment]
Hi Thierry,

I followed your suggestion and change the schedule name as “Sch 1”. The inputs are as follow

OtherEquipment,
    ZONE ONE OthEq 1,        !- Name
    Electricity,             !- Fuel Type
    ZONE ONE,                !- Zone or ZoneList Name
    Sch 1,                   !- Schedule Name
    EquipmentLevel,          !- Design Level Calculation Method
    1,                       !- Design Level {W}
    ,                        !- Power per Zone Floor Area {W/m2}
    0.000,                   !- Power per Person {W/Person}
    0,                       !- Fraction Latent
    0.3,                     !- Fraction Radiant
;                        !- Fraction Lost


ExternalInterface:FunctionalMockupUnitExport:To:Schedule,
    Sch 1,                   !- Schedule Name
    Fraction,                !- Schedule Type Limits Names
    Q,                       !- FMU Variable Name
    0;                       !- Initial Value


However, Dymola failed to initialize the input FMU file. Attached is the dymola scree. It takes forever to initializing simulation.

Please for your further instruction. Thank you a lot!!

Best,
Yuan Yuan

[cid:image001.png@01D2B84A.DD08AE30]

**Comment by tsnouidui** [comment]
@yyuanjoy your IDF contains another schedule with name Sch 1:

Schedule:Year,
    Sch 1,                   !- Name
    Fraction,                !- Schedule Type Limits Name
    Week Sch 1,              !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1

I suggest to use a different and unique name and make sure that you don't have duplicates schedule names in your IDF file.

**Comment by yyuanjoy** [comment]
It works now. Thank you!

**Comment by tsnouidui** [comment]
Great. I will then close this.
